### ISSUE TITLE
Allow multiple match/regex patterns

### ISSUE THREAD

**Issue by radomirbosak** [radomirbosak/shellcut#18]
Goal: The corresponding script will executed whenever **any** of the patterns matches

Suggested config syntax:
```
shortcuts:
- name: do something
  match:
  - AA{}BB
  - CC{}DD
  shell: echo "middle part: {}"
```
