### ISSUE TITLE
Add "shell" conditions for running the patterns

### ISSUE THREAD

**Issue by radomirbosak** [radomirbosak/shellcut#37]
Proposed config format change (the *condition* key)
```yaml
---
shortcuts:
- name: Open github issue in browser
  match: issue {}
  condition: |
    curl -I https://github.com/radomirbosak/shellcut/issues/{} | grep 'Status: 404'
  bash: xdg-open https://github.com/radomirbosak/shellcut/issues/{}
  label: issue
```

Conditions could be a part of the shell script (executor) before, but if given this proposed form, the shortcuts which fit the regex, but don't pass the condition won't be displayed if there are multiple choices available.

So, in this example a non-existent issue won't be even considered as an option.
