### ISSUE TITLE
Support regex string matching

### ISSUE THREAD

**Issue by radomirbosak** [radomirbosak/shellcut#4]
I propose this syntax:
```yaml
---
shortcuts:
- regex: ^build (.*?)-(.*?)-(.*?)$
  shell: echo you entered build {0} version {1} release {2}
```

The regex syntax used is the one from python
